#!/usr/bin/env bash

script_dir="$(printf "%q " "$(realpath -s "$0")")"
cur_dir="${script_dir%/*}"

for dir in "$cur_dir"/*/; do
  sudo mkdir -p "/etc/$(basename "$dir")"
  sudo cp -r "$dir"* "/etc/$(basename "$dir")"
done
