#!/usr/bin/env bash

script_dir="$(printf "%q " "$(realpath -s "$0")")"
cur_dir="${script_dir%/*}"

mkdir -p ~/.config

for dir in "$cur_dir"/*/; do
  ln -s "$(realpath "$dir")" ~/.config
  [[ -x "$dir"/install ]] && "$dir"/install
done
