#!/usr/bin/env zsh

script_dir="$(printf "%q " "$(realpath -s "$0")")"
cur_dir="${script_dir%/*}"

ln -s "$(realpath "$cur_dir"/.zshenv)" ~

. "$cur_dir"/.zshenv

mkdir -p "$(dirname "$HISTFILE")"
touch "$HISTFILE"
