gui:
    showFileTree: false
    skipDiscardChangeWarning: true
    theme:
        lightTheme: false
        selectedLineBgColor:
            - underline
        selectedRangeBgColor:
            - underline
git:
    paging:
        colorArg: never
        pager: delta --dark --paging=never
